apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: highload
  name: scaletest-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scaletest-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
