apiVersion: v1
kind: Namespace
metadata:
  name: highload
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: highload
  name: scaletest-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaletest-pod
  template:
    metadata:
      labels:
        app: scaletest-pod
      annotations:
        prometheus.io/scrape: "true"   # Подсказка для ServiceMonitor
        prometheus.io/port: "8080"      # Порт для сбора метрик
        prometheus.io/path: "/metrics"  # Путь для сбора метрик
    spec:
      containers:
      - name: scale-test-app
        image: ghcr.io/yandex-practicum/scaletestapp
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "30Mi"
            cpu: "500m"
          limits:
            memory: "60Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
          name: scaletest-port
---
apiVersion: v1
kind: Service
metadata:
  name: scaletest-service
  namespace: highload
  labels:
    app: scaletest-service
spec:
  selector:
    app: scaletest-pod
  ports:
  - name: http
    port: 80
    targetPort: scaletest-port
    nodePort: 30000
  - name: metrics
    port: 8080
    targetPort: scaletest-port
    nodePort: 30001
  type: NodePort
