http {
    limit_req_zone $binary_remote_addr zone=req_limit_zone:10m rate=10r/m;

    upstream backend_servers {
        server server-mock:80;
    }

    server {
        listen 80;
        limit_req zone=req_limit_zone;
        limit_req_status 429;

        location / {
            proxy_pass http://backend_servers;
        }
    }
}

events {}
